export enum VoucherType {
  ACCOUNTING_NOTE = 'ACCOUNTING_NOTE',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  CASH_RECEIPT = 'CASH_RECEIPT',
  SALES_INVOICE = 'SALES_INVOICE',
  PURCHASE_INVOICE = 'PURCHASE_INVOICE',
  PAYROLL = 'PAYROLL',
  PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
  VOUCHER = 'VOUCHER'
}